/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppActionsRouteImport } from './routes/app/actions'
import { Route as AppCriteriaRouteImport } from './routes/app/criteria'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppDossierRouteImport } from './routes/app/dossier'
import { Route as AppEvidenceRouteImport } from './routes/app/evidence'
import { Route as AppFieldRouteImport } from './routes/app/field'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppNonconformitiesRouteImport } from './routes/app/nonconformities'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as ApiActionsEvidenceUploadRouteImport } from './routes/api/actions/evidence-upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as ApiEvidenceUploadRouteImport } from './routes/api/evidence/upload'
import { Route as ApiFilesPrivateRouteImport } from './routes/api/files/private'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiOfflineActivateRouteImport } from './routes/api/offline/activate'
import { Route as ApiOfflineBootstrapRouteImport } from './routes/api/offline/bootstrap'
import { Route as ApiOfflineEvidenceUploadRouteImport } from './routes/api/offline/evidence-upload'
import { Route as ApiOfflineSyncRouteImport } from './routes/api/offline/sync'
import { Route as AppInspectionsIndexRouteImport } from './routes/app/inspections/index'
import { Route as AppInspectionsInspectionIdRouteImport } from './routes/app/inspections/$inspectionId'
import { Route as AppInspectionsNewRouteImport } from './routes/app/inspections/new'
import { Route as AppRequirementsIndexRouteImport } from './routes/app/requirements/index'
import { Route as AppRequirementsReqIdRouteImport } from './routes/app/requirements/$reqId'
import { Route as AppSilosIndexRouteImport } from './routes/app/silos/index'
import { Route as AppSilosSiloIdRouteImport } from './routes/app/silos/$siloId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCriteriaRoute = AppCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDossierRoute = AppDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiActionsEvidenceUploadRoute =
  ApiActionsEvidenceUploadRouteImport.update({
    id: '/api/actions/evidence-upload',
    path: '/api/actions/evidence-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceUploadRoute = ApiEvidenceUploadRouteImport.update({
  id: '/api/evidence/upload',
  path: '/api/evidence/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesPrivateRoute = ApiFilesPrivateRouteImport.update({
  id: '/api/files/private',
  path: '/api/files/private',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfflineActivateRoute = ApiOfflineActivateRouteImport.update({
  id: '/api/offline/activate',
  path: '/api/offline/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfflineBootstrapRoute = ApiOfflineBootstrapRouteImport.update({
  id: '/api/offline/bootstrap',
  path: '/api/offline/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfflineEvidenceUploadRoute =
  ApiOfflineEvidenceUploadRouteImport.update({
    id: '/api/offline/evidence-upload',
    path: '/api/offline/evidence-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOfflineSyncRoute = ApiOfflineSyncRouteImport.update({
  id: '/api/offline/sync',
  path: '/api/offline/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInspectionsIndexRoute = AppInspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInspectionsInspectionIdRoute =
  AppInspectionsInspectionIdRouteImport.update({
    id: '/inspections/$inspectionId',
    path: '/inspections/$inspectionId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInspectionsNewRoute = AppInspectionsNewRouteImport.update({
  id: '/inspections/new',
  path: '/inspections/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequirementsIndexRoute = AppRequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequirementsReqIdRoute = AppRequirementsReqIdRouteImport.update({
  id: '/requirements/$reqId',
  path: '/requirements/$reqId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSilosIndexRoute = AppSilosIndexRouteImport.update({
  id: '/silos/',
  path: '/silos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSilosSiloIdRoute = AppSilosSiloIdRouteImport.update({
  id: '/silos/$siloId',
  path: '/silos/$siloId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/app/actions': typeof AppActionsRoute
  '/app/criteria': typeof AppCriteriaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/dossier': typeof AppDossierRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/field': typeof AppFieldRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/api/actions/evidence-upload': typeof ApiActionsEvidenceUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/files/private': typeof ApiFilesPrivateRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/offline/activate': typeof ApiOfflineActivateRoute
  '/api/offline/bootstrap': typeof ApiOfflineBootstrapRoute
  '/api/offline/evidence-upload': typeof ApiOfflineEvidenceUploadRoute
  '/api/offline/sync': typeof ApiOfflineSyncRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
  '/app/silos/': typeof AppSilosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/app/actions': typeof AppActionsRoute
  '/app/criteria': typeof AppCriteriaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/dossier': typeof AppDossierRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/field': typeof AppFieldRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/api/actions/evidence-upload': typeof ApiActionsEvidenceUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/files/private': typeof ApiFilesPrivateRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/offline/activate': typeof ApiOfflineActivateRoute
  '/api/offline/bootstrap': typeof ApiOfflineBootstrapRoute
  '/api/offline/evidence-upload': typeof ApiOfflineEvidenceUploadRoute
  '/api/offline/sync': typeof ApiOfflineSyncRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/requirements': typeof AppRequirementsIndexRoute
  '/app/silos': typeof AppSilosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/app/actions': typeof AppActionsRoute
  '/app/criteria': typeof AppCriteriaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/dossier': typeof AppDossierRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/field': typeof AppFieldRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/api/actions/evidence-upload': typeof ApiActionsEvidenceUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/files/private': typeof ApiFilesPrivateRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/offline/activate': typeof ApiOfflineActivateRoute
  '/api/offline/bootstrap': typeof ApiOfflineBootstrapRoute
  '/api/offline/evidence-upload': typeof ApiOfflineEvidenceUploadRoute
  '/api/offline/sync': typeof ApiOfflineSyncRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
  '/app/silos/': typeof AppSilosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/app/actions'
    | '/app/criteria'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/dossier'
    | '/app/evidence'
    | '/app/field'
    | '/app/files'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/overview'
    | '/app/settings'
    | '/api/actions/evidence-upload'
    | '/api/auth/$'
    | '/api/documents/upload'
    | '/api/evidence/upload'
    | '/api/files/private'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/offline/activate'
    | '/api/offline/bootstrap'
    | '/api/offline/evidence-upload'
    | '/api/offline/sync'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections/'
    | '/app/requirements/'
    | '/app/silos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/app/actions'
    | '/app/criteria'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/dossier'
    | '/app/evidence'
    | '/app/field'
    | '/app/files'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/overview'
    | '/app/settings'
    | '/api/actions/evidence-upload'
    | '/api/auth/$'
    | '/api/documents/upload'
    | '/api/evidence/upload'
    | '/api/files/private'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/offline/activate'
    | '/api/offline/bootstrap'
    | '/api/offline/evidence-upload'
    | '/api/offline/sync'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections'
    | '/app/requirements'
    | '/app/silos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/app/actions'
    | '/app/criteria'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/dossier'
    | '/app/evidence'
    | '/app/field'
    | '/app/files'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/overview'
    | '/app/settings'
    | '/api/actions/evidence-upload'
    | '/api/auth/$'
    | '/api/documents/upload'
    | '/api/evidence/upload'
    | '/api/files/private'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/offline/activate'
    | '/api/offline/bootstrap'
    | '/api/offline/evidence-upload'
    | '/api/offline/sync'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections/'
    | '/app/requirements/'
    | '/app/silos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ApiActionsEvidenceUploadRoute: typeof ApiActionsEvidenceUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
  ApiEvidenceUploadRoute: typeof ApiEvidenceUploadRoute
  ApiFilesPrivateRoute: typeof ApiFilesPrivateRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiOfflineActivateRoute: typeof ApiOfflineActivateRoute
  ApiOfflineBootstrapRoute: typeof ApiOfflineBootstrapRoute
  ApiOfflineEvidenceUploadRoute: typeof ApiOfflineEvidenceUploadRoute
  ApiOfflineSyncRoute: typeof ApiOfflineSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/criteria': {
      id: '/app/criteria'
      path: '/criteria'
      fullPath: '/app/criteria'
      preLoaderRoute: typeof AppCriteriaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dossier': {
      id: '/app/dossier'
      path: '/dossier'
      fullPath: '/app/dossier'
      preLoaderRoute: typeof AppDossierRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/field': {
      id: '/app/field'
      path: '/field'
      fullPath: '/app/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nonconformities': {
      id: '/app/nonconformities'
      path: '/nonconformities'
      fullPath: '/app/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/actions/evidence-upload': {
      id: '/api/actions/evidence-upload'
      path: '/api/actions/evidence-upload'
      fullPath: '/api/actions/evidence-upload'
      preLoaderRoute: typeof ApiActionsEvidenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/upload': {
      id: '/api/evidence/upload'
      path: '/api/evidence/upload'
      fullPath: '/api/evidence/upload'
      preLoaderRoute: typeof ApiEvidenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/private': {
      id: '/api/files/private'
      path: '/api/files/private'
      fullPath: '/api/files/private'
      preLoaderRoute: typeof ApiFilesPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offline/activate': {
      id: '/api/offline/activate'
      path: '/api/offline/activate'
      fullPath: '/api/offline/activate'
      preLoaderRoute: typeof ApiOfflineActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offline/bootstrap': {
      id: '/api/offline/bootstrap'
      path: '/api/offline/bootstrap'
      fullPath: '/api/offline/bootstrap'
      preLoaderRoute: typeof ApiOfflineBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offline/evidence-upload': {
      id: '/api/offline/evidence-upload'
      path: '/api/offline/evidence-upload'
      fullPath: '/api/offline/evidence-upload'
      preLoaderRoute: typeof ApiOfflineEvidenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offline/sync': {
      id: '/api/offline/sync'
      path: '/api/offline/sync'
      fullPath: '/api/offline/sync'
      preLoaderRoute: typeof ApiOfflineSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inspections/': {
      id: '/app/inspections/'
      path: '/inspections'
      fullPath: '/app/inspections/'
      preLoaderRoute: typeof AppInspectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/$inspectionId': {
      id: '/app/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/app/inspections/$inspectionId'
      preLoaderRoute: typeof AppInspectionsInspectionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/new': {
      id: '/app/inspections/new'
      path: '/inspections/new'
      fullPath: '/app/inspections/new'
      preLoaderRoute: typeof AppInspectionsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/requirements/': {
      id: '/app/requirements/'
      path: '/requirements'
      fullPath: '/app/requirements/'
      preLoaderRoute: typeof AppRequirementsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/requirements/$reqId': {
      id: '/app/requirements/$reqId'
      path: '/requirements/$reqId'
      fullPath: '/app/requirements/$reqId'
      preLoaderRoute: typeof AppRequirementsReqIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/silos/': {
      id: '/app/silos/'
      path: '/silos'
      fullPath: '/app/silos/'
      preLoaderRoute: typeof AppSilosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/silos/$siloId': {
      id: '/app/silos/$siloId'
      path: '/silos/$siloId'
      fullPath: '/app/silos/$siloId'
      preLoaderRoute: typeof AppSilosSiloIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppCriteriaRoute: typeof AppCriteriaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDossierRoute: typeof AppDossierRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppFieldRoute: typeof AppFieldRoute
  AppFilesRoute: typeof AppFilesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppInspectionsInspectionIdRoute: typeof AppInspectionsInspectionIdRoute
  AppInspectionsNewRoute: typeof AppInspectionsNewRoute
  AppRequirementsReqIdRoute: typeof AppRequirementsReqIdRoute
  AppSilosSiloIdRoute: typeof AppSilosSiloIdRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
  AppRequirementsIndexRoute: typeof AppRequirementsIndexRoute
  AppSilosIndexRoute: typeof AppSilosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppCriteriaRoute: AppCriteriaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDossierRoute: AppDossierRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppFieldRoute: AppFieldRoute,
  AppFilesRoute: AppFilesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppInspectionsInspectionIdRoute: AppInspectionsInspectionIdRoute,
  AppInspectionsNewRoute: AppInspectionsNewRoute,
  AppRequirementsReqIdRoute: AppRequirementsReqIdRoute,
  AppSilosSiloIdRoute: AppSilosSiloIdRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
  AppRequirementsIndexRoute: AppRequirementsIndexRoute,
  AppSilosIndexRoute: AppSilosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ApiActionsEvidenceUploadRoute: ApiActionsEvidenceUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
  ApiEvidenceUploadRoute: ApiEvidenceUploadRoute,
  ApiFilesPrivateRoute: ApiFilesPrivateRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiOfflineActivateRoute: ApiOfflineActivateRoute,
  ApiOfflineBootstrapRoute: ApiOfflineBootstrapRoute,
  ApiOfflineEvidenceUploadRoute: ApiOfflineEvidenceUploadRoute,
  ApiOfflineSyncRoute: ApiOfflineSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
