/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppActionsRouteImport } from './routes/app/actions'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppEvidenceRouteImport } from './routes/app/evidence'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppNonconformitiesRouteImport } from './routes/app/nonconformities'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppInspectionsIndexRouteImport } from './routes/app/inspections/index'
import { Route as AppInspectionsNewRouteImport } from './routes/app/inspections/new'
import { Route as AppRequirementsIndexRouteImport } from './routes/app/requirements/index'
import { Route as AppRequirementsReqIdRouteImport } from './routes/app/requirements/$reqId'
import { Route as AppSilosIndexRouteImport } from './routes/app/silos/index'
import { Route as AppSilosSiloIdRouteImport } from './routes/app/silos/$siloId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNonconformitiesRoute = AppNonconformitiesRouteImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInspectionsIndexRoute = AppInspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInspectionsNewRoute = AppInspectionsNewRouteImport.update({
  id: '/inspections/new',
  path: '/inspections/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequirementsIndexRoute = AppRequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequirementsReqIdRoute = AppRequirementsReqIdRouteImport.update({
  id: '/requirements/$reqId',
  path: '/requirements/$reqId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSilosIndexRoute = AppSilosIndexRouteImport.update({
  id: '/silos/',
  path: '/silos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSilosSiloIdRoute = AppSilosSiloIdRouteImport.update({
  id: '/silos/$siloId',
  path: '/silos/$siloId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
  '/app/silos/': typeof AppSilosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/requirements': typeof AppRequirementsIndexRoute
  '/app/silos': typeof AppSilosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/nonconformities': typeof AppNonconformitiesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/requirements/$reqId': typeof AppRequirementsReqIdRoute
  '/app/silos/$siloId': typeof AppSilosSiloIdRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
  '/app/silos/': typeof AppSilosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/evidence'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/settings'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections/'
    | '/app/requirements/'
    | '/app/silos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/evidence'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/settings'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections'
    | '/app/requirements'
    | '/app/silos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/evidence'
    | '/app/history'
    | '/app/nonconformities'
    | '/app/settings'
    | '/app/inspections/new'
    | '/app/requirements/$reqId'
    | '/app/silos/$siloId'
    | '/app/inspections/'
    | '/app/requirements/'
    | '/app/silos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nonconformities': {
      id: '/app/nonconformities'
      path: '/nonconformities'
      fullPath: '/app/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/': {
      id: '/app/inspections/'
      path: '/inspections'
      fullPath: '/app/inspections/'
      preLoaderRoute: typeof AppInspectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/new': {
      id: '/app/inspections/new'
      path: '/inspections/new'
      fullPath: '/app/inspections/new'
      preLoaderRoute: typeof AppInspectionsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/requirements/': {
      id: '/app/requirements/'
      path: '/requirements'
      fullPath: '/app/requirements/'
      preLoaderRoute: typeof AppRequirementsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/requirements/$reqId': {
      id: '/app/requirements/$reqId'
      path: '/requirements/$reqId'
      fullPath: '/app/requirements/$reqId'
      preLoaderRoute: typeof AppRequirementsReqIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/silos/': {
      id: '/app/silos/'
      path: '/silos'
      fullPath: '/app/silos/'
      preLoaderRoute: typeof AppSilosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/silos/$siloId': {
      id: '/app/silos/$siloId'
      path: '/silos/$siloId'
      fullPath: '/app/silos/$siloId'
      preLoaderRoute: typeof AppSilosSiloIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppInspectionsNewRoute: typeof AppInspectionsNewRoute
  AppRequirementsReqIdRoute: typeof AppRequirementsReqIdRoute
  AppSilosSiloIdRoute: typeof AppSilosSiloIdRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
  AppRequirementsIndexRoute: typeof AppRequirementsIndexRoute
  AppSilosIndexRoute: typeof AppSilosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppInspectionsNewRoute: AppInspectionsNewRoute,
  AppRequirementsReqIdRoute: AppRequirementsReqIdRoute,
  AppSilosSiloIdRoute: AppSilosSiloIdRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
  AppRequirementsIndexRoute: AppRequirementsIndexRoute,
  AppSilosIndexRoute: AppSilosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
